#!/usr/bin/env python3
"""Regenera assets/atlas.png (medieval) pixel-identico."""
import struct, zlib
PAL = {'A': (138, 111, 82), 'B': (106, 83, 66), 'C': (87, 66, 47), 'D': (69, 51, 36), 'E': (156, 144, 128), 'F': (132, 119, 103), 'G': (103, 95, 85), 'H': (78, 70, 60), 'I': (217, 180, 137), 'J': (169, 136, 95), 'K': (156, 134, 96), 'L': (117, 94, 70), 'M': (87, 67, 46), 'N': (58, 46, 32), 'O': (134, 162, 78), 'P': (95, 122, 54), 'Q': (66, 89, 42), 'R': (46, 64, 32), 'S': (244, 246, 246), 'T': (217, 226, 226), 'U': (73, 86, 91), 'V': (55, 65, 68), 'W': (46, 42, 38), 'X': (247, 209, 84), 'Y': (224, 138, 30), 'Z': (156, 74, 18)}
TILES = [
  ['POOOPPQPPPQRPQOQ', 'POOPQOQPPQPQQQOP', 'OOPPPPQPOPPQPPPP', 'OOPROPOPQPPPPPOP', 'PPPPPPOROOPPPOPP', 'POPPPPPPOPOOPPQR', 'OPPOPPPPQQQPOOOP', 'OOQPPOPQPOOPPOPP', 'QQQPQPOPPQPPOOPP', 'OPPPPPPOPOPPPOQP', 'POQOOOPPPQOQPOQO', 'POPPOPOOQPOPPPPP', 'RPPPPPQROOPRPOQO', 'PPOPPPPRPQPPPPPR', 'OPPPQPOPQOPORPPP', 'PPOPPOPOOORPQOPO'],
  ['OOOOOOOOOOOPPOOO', 'PPPPPOPQPPPQQQPP', 'OQPPPPOPQOQOPPQP', 'PQPPQQOOOPPQQQOO', 'QQPPAAQQQPOBBQQQ', 'AAQQBBBBAQQCBACB', 'BABAACBBBAAAABBC', 'BABBABABCBBBAACB', 'BABBCBBBBBABBBAC', 'AABCBABBCCBBABBB', 'BCBBBCBAACBABABB', 'ABCACBABBBBBAABA', 'AAAAAAABBBBBCBAC', 'ABBABABBAAABBBCB', 'BBBABAABCAABAAAB', 'ABBABBBCAAABCBBC'],
  ['CABBABABBABAACBB', 'CBBABBBAABCADBCC', 'BABCBBACBABCBBBA', 'BAABCAACBBDBBBAD', 'CAABABAAABCABBBA', 'BABBBABACABBBBDA', 'BBABBBCABBBBACCB', 'AACABABCBBBBABBA', 'ABBABABBBBBCABBC', 'CBBABABBBBAAAABA', 'ABDBBAABACABABDA', 'AAACBDABABBBAABB', 'BABBACBCAACCDBBB', 'CBCBADBABABBABAB', 'BCBDBBBABAACBBBB', 'DBBBABCAABBBBCBB'],
  ['FFGFFFEFFEFFEFEF', 'FFFEFFGGHEEFEFEF', 'FEEFFEFGEHFGFFFE', 'FFFFEHFHFEFEEEFG', 'FEGFGFEFFFHFEGFF', 'FHFFFEEGEFFHEFEF', 'EFFEEGFFEFHFFFFE', 'FFFEFFGFGFHHFFHF', 'FFFFFFFFFHFFFFEH', 'EHFEFEFGGGFFFFFE', 'FFFFEFFFEGEFFGFF', 'EEFFFEFFGFFFEEFF', 'EGFFFGGFFEFFFFFF', 'GFFEFFFFEFFEEFFE', 'HFEGEFGFGGFFEFFF', 'FFFFFEFFFFEFFEEF'],
  ['IIJIIIIIIIIJIIIA', 'IIIIIIIIJIIJJIJJ', 'JIIIJIIIIIIJJJII', 'JJAIIIAIIIIJIJAI', 'IIIIJJIJIIJIIIII', 'IIIJJIIIJIIIIIII', 'IIIJJJJIJAJJJJIJ', 'JIIJIAIIIJIJIIIJ', 'IIIIIAIIIAIJIJII', 'IIIIJJIJIIIIJJJI', 'JJIIIIJIIIIJIIIJ', 'JIIJIIJIIIIIAIII', 'JIJAJIIJJIJIIAAI', 'IIIIIIJAJIIJIJJI', 'JIJIIJIIJJIIIIIJ', 'IIIIJJIIJJIJJIII'],
  ['LLNLLMMLLNLLLLNL', 'LLNLLLMLLNLLLMNL', 'LLNLKMLLLNLLLLNL', 'LLNLKMLLLNLKLLNL', 'LLNLKMLMLNMKLLNL', 'MLNMKLLLLNLKMLNL', 'LLNLKLMKKNLKLLNL', 'LLNLKLMNNNLKLLNL', 'LLNLKLLNNNLKLLNL', 'LLNMKLLLMNLKLLNM', 'LLNLKMLLLNLKLLNM', 'LLNLKLMLLNLKLLNL', 'LLNLKLMLMNLKMLNL', 'LLNLKLLLLNLLLLNL', 'LLNLLLMLLNLLLLNL', 'LLNLLMLLMNLLLMNL'],
  ['NNNNNNNNNNNNNNNN', 'NLLLLLLLLLLLLLLN', 'NLLKKKKKKKKKKLLN', 'NLKLLLLLLLLLLKLN', 'NLKLLMMMMMMLLKLN', 'NLKLNLLLLLLMLKLN', 'NLKLMLLKKLLMLKLN', 'NLKLMLKMMKLNLKLN', 'NLKLMLKMMKLNLKLN', 'NLKLMLLKKLLNLKLN', 'NLKLMLLLLLLMLKLN', 'NLKLLMMMMMMLLKLN', 'NLKLLLLLLLLLLKLN', 'NLLKKKKKKKKKKLLN', 'NLLLLLLLLLLLLLLN', 'NNNNNNNNNNNNNNNN'],
  ['QPPQPQQQRPPQPPPQ', 'PPQPQPQQQQQPPPQQ', 'PPRQQPQQPQRPQQ.Q', 'QQPQ..QPQPPPQQ.Q', 'PPPP..QQQQQPQQPP', 'QQQOQPQQQPP..PPQ', 'QQQPQRPQP....QQQ', 'PPQPOPPQPPQQQPQQ', 'QPPQPQ..OPQQPQQP', 'PPQQQP..QQPOMMPQ', 'QQ..PQQPQQOQ..PP', 'PQPQQRPMMQPQ..PP', 'PQQQQPQ...QQQQPP', 'QP..QQQ...PPQ..Q', 'PPQRQQQQPQQPPPQQ', 'PQQPQQPRQQQPPQPQ'],
  ['........Y.......', '.......YYY......', '......YXXY......', '......YXYY......', '......YYYY......', '......ZYYZ......', '.......ZZ.......', '.......LM.......', '.......LM.......', '.......LM.......', '.......LM.......', '.......LM.......', '.......LM.......', '.......LM.......', '.......LM.......', '.......LM.......'],
  ['SSTSTSTSSSTSTSTS', 'TSSTTTSTSTTSSTSS', 'SSSSSTSSTTSSTSSS', 'SSSSSSSSTSSSTTST', 'TSSTSSTTTSSTSSTT', 'TSSTSSSSSSSTSSSS', 'SSSTSSSSSTTSSSSS', 'STTSSSTTSSTSTSTT', 'TSSTSTTSTSSTTTST', 'SSSSTTSSSTSTTSSS', 'TTTSTTTSTTTTTSSS', 'STTTTSSSTTTTTTSS', 'SSSSSSTTTTTTTTST', 'TSSSSSTSSSSTSSSS', 'SSSSSSSSSSSSTSSS', 'TSSSTTSSSSSTSSSS'],
  ['VVVVVVVVVVVVVVVV', 'VVVVVVVVVVVVVVVV', 'VVVVVVVVVVVVVVVV', 'VVVVVVVVSSVVVVVV', 'SSVVVVVVUUUUUUVV', 'UUUUUUVVVUUUVVVV', 'VVVVVVVVVVVVVVSV', 'VVVVVVVVVVVUUUSV', 'VVVSSVVVVVVVVVVV', 'VVVUUUUUUVVVVVVV', 'VVVVVVVVVVVVVVVV', 'VVVVVVVVVVVVVVVV', 'VVVVVVVVVUUUUUVV', 'VVVVVVVVVVVVVVVV', 'VVVVVSSVVVVVVVVV', 'VVVVVVVVVVVVVVVV'],
  ['LLLLLMMLLMLNMLLL', 'LLMMLMLLLMLNLMLM', 'LMMMLLLLMLMNLLLM', 'NNNNNNNNNNNNNNNN', 'LLKLNLLLLLLLLKLK', 'LLLKNKMMKLLLLLLL', 'LLKLNLKLLLLLLLLL', 'NNNNNNNNNNNNNNNN', 'LMLLLKNLNLLMLLLL', 'MLLLLLNLNLLMMLLL', 'MLLLLLLMNLLLLLLL', 'NNNNNNNNNNNNNNNN', 'LLLLLLLKLLLKLNLL', 'KLLMMLLLLLLLLNLK', 'LKLLLKLLLLLLKNLL', 'NNNNNNNNNNNNNNNN'],
  ['NNNNNNNNNNNNNNNN', 'NNNNNNNNNNNNNNNN', 'LLNNKKKKKKKKNNLL', 'LLNNLLMLLLLLNNLM', 'MLNNLMLLLLLLNNML', 'LLNNLLLLLLLLNNLL', 'LLNNLLLLLLLLNNLM', 'LLNNLLMLLMLLNNLL', 'LLNNLLMMMMLLNNLL', 'LLNNLMLLLLLLNNLL', 'LLNNMLLLMMMLNNLL', 'LLNNLLLLLLLLNNLL', 'LMNNLMLLLMLMNNLL', 'LMNNLLLLMLMLNNLL', 'NNNNNNNNNNNNNNNN', 'NNNNNNNNNNNNNNNN'],
  ['NNNNNNNNNNNNNNNN', 'NLLKLMLLLLMLLLLN', 'NLLLLMLLLKMLLLLN', 'NLLLLMLLLLMKLLLN', 'NLLLLMLLLLMLKLLN', 'NMMMMMMMMMMMMMMN', 'NLLLLMKLLLMLLLKN', 'NLKLLMLMMLMLLLKN', 'NLLLLMKMMLMLLLKN', 'NLLLLMLKLLMLLLLN', 'NMMMMMMMMMMMMMMN', 'NLLLLMLLLLMLLLLN', 'NKLKLMLLLLMKLLLN', 'NLLLLMLLLLMLLLLN', 'NLLLKMLLKLMLLLKN', 'NNNNNNNNNNNNNNNN'],
  ['BAABBCBBABBCABBB', 'BBBBCABBABBCBBBA', 'BAABBBABBCBBBBBB', 'BABBBBBBABAABBAB', 'BBCCCBBBBBAABAAA', 'BBBBBAABCAACBCBB', 'BABBBCFFBABABBCA', 'BABBAAFFCACBBBAC', 'CBBBBBBCCBBBAABA', 'BBBABABBCBBBCBBB', 'BBABBCBBBBBFFABB', 'CCBEEBBBBBBFFBBB', 'ABBCABBACABBCBCB', 'ABBBAABBABBABBCB', 'BBBBAABBBBBBCBBC', 'BBBAABBBBBABBBAB'],
  ['HHHHHHHHHHHHHHHH', 'HHHHHHHHIIIHHHHH', 'HHEEEEHHJJJHHHHH', 'HHFFFFHHJJJHHHHH', 'HHFFFFHHHHHHHHHH', 'HHHHHHHHHHHEEEHH', 'HHHHHHHHHHHFFFHH', 'HHHHHHHHHHHFFFHH', 'HHHIIIIHHHHHHHHH', 'HHHAAAAHHHHHHHHH', 'HHHAAAAHHHHHHHHH', 'HHHHHHHHHFFFFHHH', 'HHHHHHHHHGGGGHHH', 'HHHHHHHHHGGGGEEH', 'HHHHHHHHHHHHHHHH', 'HHHHHHHHHHHHHHHH'],
  ['DMMBBDBBCCBMBCBC', 'BCCCCCCCCCMCMCBM', 'BCMCMCBCBCDMDCBD', 'BMBBCBMBMCMMCMBC', 'CCBCBCBCBMCCBMCM', 'CMCCCCBCBBCCCBBM', 'BBDCCCBBCBMBMMMB', 'CDBMCCBCBBBMCDBM', 'BCCBCMMCCCCCCCCM', 'BCCBCBMBDBBCMMBM', 'MCCCCMBDBCMCBCCC', 'BCBCMCCBCCBBBCCM', 'BMCCBCBBCMCBBDMC', 'CCCCMCCDDCCCBMDM', 'CBCCMCMBCMCMBBCB', 'CBCCCBBBBBCCBBBC'],
  ['YYYYYYYYYYYYYYYY', 'YYYYYYYYYYYYYYYY', 'YYYXXXYYYYYYYYYY', 'YYXXXXXYYYZZZZYY', 'YYXXXXXYYYZZZZYY', 'YYYXXXYYYYYYZZZY', 'YYYYYYNYYYYYZZZY', 'YYYYYYNZZZZYYNYY', 'YYYYYYNYYYYYYNYY', 'YYZZZZYYYYXXXXYY', 'YYZZZZYYYXXXXXXY', 'YYYYYYYYYYXXXXYY', 'YYYYYYYYYNNXXYYY', 'YYYYYYYYYYYZZZYY', 'YYYYYYYYYYYYYYYY', 'YYYYYYYYYYYYYYYY'],
  ['EHHWWWWWHWWWWHWW', 'WWWWWWHWWGHWWWWH', 'WWWWWWHWGWWWWHWW', 'HWHWGWHWHGWWEWWW', 'WHWWWGHWGWHWWWWG', 'HWWWWWWWWWHWHWWW', 'WHWWHWWHWWHWHWWW', 'WHHHWWWWWWWWHHHW', 'WWWGHWWWHWHWWHWW', 'HWHWWWWWHWWGGHWG', 'WWWWWWWWHWWWWWHW', 'WWWWGWWHGEGWWWWW', 'WWHHWHHWWWHWHWWW', 'WWHWWHWHWWWWWWWW', 'GHWWWWWWHWWWWWGW', 'GWHWHWWWWWHWWWWG'],
]
W, H = 64, 80
px = bytearray(W * H * 4)
for n in range(19):
    col, row = n % 4, n // 4
    for y in range(16):
        for x in range(16):
            ch = TILES[n][y][x]
            i = ((row * 16 + y) * W + (col * 16 + x)) * 4
            if ch == ".":
                px[i:i+4] = bytes((0, 0, 0, 0))
            else:
                r, g, b = PAL[ch]
                px[i:i+4] = bytes((r, g, b, 175 if n == 10 else 255))
def chunk(t, d):
    return struct.pack(">I", len(d)) + t + d + struct.pack(">I", zlib.crc32(t + d) & 0xffffffff)
raw = b"".join(b"\x00" + bytes(px[r * W * 4:(r + 1) * W * 4]) for r in range(H))
png = b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", struct.pack(">IIBBBBB", W, H, 8, 6, 0, 0, 0)) + chunk(b"IDAT", zlib.compress(bytes(raw), 9)) + chunk(b"IEND", b"")
open("assets/atlas.png", "wb").write(png)
print("atlas medieval regenerado:", len(png), "bytes")
