#!/usr/bin/env python3
"""Regenera assets/atlas.png byte-identico al pintado en LibreSprite."""
import struct, zlib
PAL = {'A': (224, 166, 103), 'B': (168, 101, 50), 'C': (95, 52, 25), 'D': (185, 196, 209), 'E': (125, 140, 160), 'F': (74, 87, 110), 'G': (232, 163, 61), 'H': (176, 99, 31), 'I': (94, 47, 18), 'J': (205, 225, 78), 'K': (95, 176, 43), 'L': (31, 107, 58), 'M': (18, 58, 38), 'N': (255, 226, 122), 'O': (242, 168, 29), 'P': (156, 83, 16), 'Q': (125, 232, 224), 'R': (43, 200, 200), 'S': (16, 88, 107), 'T': (255, 154, 138), 'U': (226, 58, 58), 'V': (110, 20, 48), 'W': (255, 243, 214), 'X': (203, 210, 218), 'Y': (35, 43, 61), 'Z': (255, 255, 255), '*': (255, 230, 0), '+': (255, 46, 136)}
TILES = [
  ['KKKKKKKKKKKKKKKK', 'KKKKKKKKKKKKKKKK', 'KKJJJJKKKKKKKKKK', 'KKJJJJKKKKKJJKKK', 'KKKJJKKKKKKJJKKK', 'KKKKKKKKKKKKKKKK', 'KKKKKKKKKKKKKKKK', 'KKKKKKKKKKKKKKKK', 'KKKKKKKKKKKKKKKK', 'KKKKKKKKKKKKKKKK', 'KKKKKKKKKKLLLKKK', 'KKKLLKKKKLLLLLKK', 'KKKLKKKKKKLLLKKK', 'KKKKKKKKKKKKKKKK', 'KKKKKKKKKKKKKKKK', 'KKKKKKKKKKKKKKKK'],
  ['JJJJKKJJJJJKKJJJ', 'KKKKKKKKKKKKKKKK', 'KKKKBBKKKKKBBKKK', 'LLKKBBLLLKKBBLLL', 'BBLLBBBBBLLBBBBB', 'BBBBBBBBBBBBBBBB', 'BBBBAABBBBBBBBBB', 'BBBBBCCBBBBBBBBB', 'BBBBBCCCBBBBBBBB', 'BBBBBBBBBBBBBBBB', 'BBBBBBBBBBBBBBBB', 'BBBBBBBBBBBBBBBB', 'BBBBBBBBBBBBBBBB', 'BBBBBBBBBBBBBBBB', 'BBBBBBBBBBBBBBBB', 'BBBBBBBBBBBBBBBB'],
  ['BBBBBBBBBBBBBBBB', 'BBBBBBBBBBBBBBBB', 'BBBBBBBBBBBBBBBB', 'BBBCCBBBBBBBBBBB', 'BBBCBBBBBBBBBBBB', 'BBBBBBBBBBBBAABB', 'BBBBBBBBBBBBBBBB', 'BBBBBBBBBBBBBBBB', 'BBBBBBBBBAABBBBB', 'BBBBBBBBBCCCCBBB', 'BBBBBBBBBCCCCCBB', 'BBBBBBBBBCCCCBBB', 'BBBBBBBBBBCCBBBB', 'BBBBBBBBBBBBBBBB', 'BBBBBBBBBBBBBBBB', 'BBBBBBBBBBBBBBBB'],
  ['EEEEEEEEEEEEEEEE', 'EEEEEEEEEEEEEEEE', 'EEDDDEEEEEEEEEEE', 'EEDDDEEEEEEEEEEE', 'EEFFFEEEEEEEEEEE', 'EEEEEEEEEEEFEEEE', 'EEEEEEEEEEFEEEEE', 'EEEEEEEEEEFEEEEE', 'EEEEEEEEEFEEEEEE', 'EEEEEEEEFEEEEEEE', 'EEEEEEEEEEEEEEEE', 'EEEEEEEEEEEEEDEE', 'EEEEEEEEEEEEEDEE', 'EEEEEEEEEEEEEEEE', 'EEEEEEEEEEEEEEEE', 'EEEEEEEEEEEEEEEE'],
  ['AAAAAAAAAAAAAAAA', 'AAAAAAAAAAAAAAAA', 'AAAAAAAAAAAAAAAA', 'AAAAAAAAAAAAAAAA', 'AAAAAAAAAAAWWAAA', 'AAAAAAAAAAAAAAAA', 'AAABBAAAAAAAAAAA', 'AAAAAAAAAAAAAAAA', 'AAAAAAAAAAAAAAAA', 'AAAAAAAAAAAAAAAA', 'AAAAAAAAAAAAAAAA', 'AAAAABBBBAAAAAAA', 'AAAAAABBAAAAAAAA', 'AAAAAAAAAAAAAAAA', 'AAAAAAAAAAAAAAAA', 'AAAAAAAAAAAAAAAA'],
  ['HHIHHHHHHHHIHHHH', 'HHIHHHHHHHHIHHHH', 'HHIHHHHHHHHIHHHH', 'HHIHGHHHHHHIHHHH', 'HHIHGHHHHHHIHHHH', 'HHIHGHHHHHHIGHHH', 'HHIHGHHGGHHIGHHH', 'HHIHGHHCCHHIGHHH', 'HHIHGHHCCHHIGHHH', 'HHIHGHHHHHHIGHHH', 'HHIHGHHHHHHIGHHH', 'HHIHGHHHHHHIGHHH', 'HHIHHHHHHHHIGHHH', 'HHIHHHHHHHHIGHHH', 'HHIHHHHHHHHIHHHH', 'HHIHHHHHHHHIHHHH'],
  ['IIIIIIIIIIIIIIII', 'IHHHHHHHHHHHHHHI', 'IHGGHHHHHHHHHHHI', 'IHGHIIIIIIIIHHHI', 'IHHIHHHHHHHHIHHI', 'IHHIIIHHHHHHIHHI', 'IHHIHHHIIHHHIHHI', 'IHHIHHIIIIHIIHHI', 'IHHIHHIIIIHIIHHI', 'IHHIHHHIIIHIIHHI', 'IHHIHHHHHHHHIHHI', 'IHHIHHHHHHHHIHHI', 'IHHHIIIIIIIIHHHI', 'IHHHHHHHHHHHHHHI', 'IHHHHHHHHHHHHHHI', 'IIIIIIIIIIIIIIII'],
  ['KKKKKKKKKKKKKKKK', 'KKKKKKKKKKKKKKKK', 'KKJJJJKKKKKKKKKK', 'KKJJJKKKKKKKKKKK', 'KKKKKKKKKKKJJKKK', 'KKKK..KKKKKKKKKK', 'KKKKKKKKKKKKKKKK', 'KKKKKKKKKKKKK.KK', 'KKKKKKKKKKKKKKKK', 'KKKKKK.KKKKKKKKK', 'KKKKKK.KKLLLLLKK', 'KKKLKKKKKLLLLLKK', 'KKKLKKKKKKLLLKKK', 'KKKKKKKK..KKKKKK', 'KKKKKKKKKKKKKKKK', 'KKKKKKKKKKKKKKKK'],
  ['................', '.......OO.......', '......ONNO......', '......ONOO......', '......OOOO......', '......POOP......', '.......PP.......', '.......HI.......', '.......HI.......', '.......HI.......', '.......HI.......', '.......HI.......', '.......HI.......', '.......HI.......', '.......HI.......', '.......HI.......'],
  ['WWWWWWWWWWWWWWWW', 'WWWWWWWWWWWWWWWW', 'WWWWWWWWWWWWWWWW', 'WWWWWWWWWWWWZZWW', 'WWWDDWWWWWWWWWWW', 'WWWDWWWWWWWWWWWW', 'WWWWWWWWWWWWWWWW', 'WWWWWWWWWWWWWWWW', 'WWWWWWWWWWWWWWWW', 'WWWWWWWWWWWWWWWW', 'WWWWWWWWWXXXXWWW', 'WWWWWWWWXXXXXXWW', 'WWWWWWWWWXXXXWWW', 'WWWWWWWWWWWWWWWW', 'WWWWWWWWWWWWWWWW', 'WWWWWWWWWWWWWWWW'],
  ['RRRRRRRRRRRRRRRR', 'RRRRRRRRRRRRRRRR', 'RRRRRRRRRRRRRRRR', 'RQQRRRRRRQQRRRRR', 'SSSSRRRRRSSSSRRR', 'RRRRSSSRRRRRRRRR', 'RRRRRRRRRRRRRRRR', 'RRRRRRRRRRRRRQQR', 'RRRRRRRRRRRRRRRR', 'RRRRRRRRRRRRRRRR', 'RRRRRRRRRRRSSRRR', 'RRRRRRRRRRSSSSRR', 'RRRRRRRRRRRSSRRR', 'RRRRRRRRRRRRRRRR', 'RRRRRRRRRRRRRRRR', 'RRRRRRRRRRRRRRRR'],
  ['HHHHHHHHHHHIHHHH', 'HHIIHHHHHHHIHHHH', 'HGGHHHHHHHHIHHHH', 'IIIIIIIIIIIIIIII', 'HHHHIHHHHHHHHHHH', 'HHHHIHIIHHHHHHHH', 'HGGHIHHHHHHHHHHH', 'IIIIIIIIIIIIIIII', 'HHHHHGIHIHHHHHHH', 'HHHHHHIHIHHIIHHH', 'HGGHHHHHIHHHHHHH', 'IIIIIIIIIIIIIIII', 'HHHHHHHHHHHHHIHH', 'HHHIIHHHHHHHHIHH', 'HGGHHHHHHHHHHIHH', 'IIIIIIIIIIIIIIII'],
  ['IIIIIIIIIIIIIIII', 'IIIIIIIIIIIIIIII', 'HHIIGGGGGGGGIIHH', 'HHIIHHHHHHHHIIHH', 'HHIIHHHHHHHHIIHH', 'HHIIHHHHHHHHIIHH', 'HHIIHHHHHHHHIIHH', 'HHIIHHHHHHHHIIHH', 'HHIIHHIIHHHHIIHH', 'HHIIHHHHHHHHIIHH', 'HHIIHHHHHIIHIIHH', 'HHIIHHHHHHHHIIHH', 'HHIIHHHHHHHHIIHH', 'HHIIHHHHHHHHIIHH', 'IIIIIIIIIIIIIIII', 'IIIIIIIIIIIIIIII'],
  ['HHHHHHHIIHHHHHHH', 'HGIHHHHIIHHHHGIH', 'HIIHHHHIIHHHIIIH', 'HHHGGHHIIHHHHHHH', 'HHHGGHHIIHHHHHHH', 'HHHHHHHIIHHHHHHH', 'HHHHHHHIIHHHHHHH', 'IIIIIIIIIIIIIIII', 'IIIIIIIIIIIIIIII', 'HHHHHHHIIHHHHHHH', 'HHHHHHHIIHHHHHHH', 'HHHHHHHIIHHGGHHH', 'HHHHHHHIIHHGGHHH', 'HGIHHHHIIHHHHGIH', 'HIIHHHHIIHHHIIIH', 'HHHHHHHIIHHHHHHH'],
  ['BBBBBBBBBBBBBBBB', 'BBBBBBBBBBBBBBBB', 'BBBAABBBBBBBBBBB', 'BBBCCCBBBBBBBBBB', 'BBCCCCBBBBBCCBBB', 'BBBCCCBBBBBBBBBB', 'BBBBBBBBBBBBBBBB', 'BBBBBBBBBBBBBBBB', 'BBBBBBBBBBBBBBBB', 'BBBBBBBBBBBBBBBB', 'BBBBBBBBBBBAABBB', 'BBBBBBBBBBBBBBBB', 'BBBBBBBBBBBBBBBB', 'BBBBBBBBBBBBBBBB', 'BBBBBBBBBBBBBBBB', 'BBBBBBBBBBBBBBBB'],
  ['EEEEEEEEEEEEEEEE', 'EEEEEEEEEEEEEEEE', 'EEEDDEEEEEEEEEEE', 'EEDDDDEEEEEEEEEE', 'EEEDDEEEEEEEEEEE', 'EEEFFEEEEEEEEXXE', 'EEEEEEEEEEEEEEEE', 'EEEEEEEEEEEEEEEE', 'EEEEEEEEEEEEEEEE', 'EEEEEEEEEEXXEEEE', 'EEEEEEEEEEXXEEEE', 'EEEEEEFFEEEEEEEE', 'EEEEEEEEEEEEEEEE', 'EEEEEEEEEEEEWWEE', 'EEEEEEEEEEEEEEEE', 'EEEEEEEEEEEEEEEE'],
  ['CCCCCCCCCCCCCCCC', 'CCCCCCCCCCCCCCCC', 'CCCCCCCCCCCCCCCC', 'CCBBBBCCCCCCCCCC', 'CCBBBBBCCCCCCCCC', 'CCCBBBCCCCCCCCCC', 'CCCCCCCCCCCCCCCC', 'CCCCCCCCCCCCCCCC', 'CCCCCCCCPPPCCCCC', 'CCCCCCCCCCCCCCCC', 'CCCCCCCCCCCCCCCC', 'CCCCCCCCCCCCPCCC', 'CCCCCCCCCCCCPCCC', 'CCCCCCCCCCCCCCCC', 'CCCCCCCCCCCCCCCC', 'CCCCCCCCCCCCCCCC'],
  ['OOOOOOOOOOOOOOOO', 'OOOOOOOOOOOOOOOO', 'OOPPPPOOOOOOOOOO', 'OPPPPPOOOONNOOOO', 'OPPPPPOOOOOOOOOO', 'OOPPPOOOOOOOOOOO', 'OOUUNNNOOOOOOOOO', 'OOOOOOONOOOOOONO', 'OOOOOOOOOOOOOONO', 'OOOOOOOOOOPPPPOO', 'OOOOOOOOOPPPPPPO', 'OOOOOOOOOPPPPPPO', 'OOOOOOOOOOPPPPOO', 'OOOOONNOOOOPPOOO', 'OOOOOOOOOOUUUOOO', 'OOOOOOOOOOOOOOOO'],
  ['YYYYYYYYYYYYYYYY', 'YYYYYYYYYYYYYYYY', 'YYYYYYYYYYYYYYYY', 'YYYYFFYYYYYYSYYY', 'YYYFFFFYYYYYSYYY', 'YYYYFFYYYYYYSYYY', 'YYYYYYYYYYYYYYYY', 'YYYYYYYYYSSSYYYY', 'YYYYYYYYYYYYYYYY', 'YYYYYYYYYYYYYYYY', 'YYYYYXXYYYYYYYYY', 'YYYYYYYYYYYYYYYY', 'YYYYYYYYYYYYYYYY', 'YYYYYYYYYYYYYYYY', 'YYYYYYYYYYYYYYYY', 'YYYYYYYYYYYYYYYY'],
]
W, H, ALPHA10 = 64, 80, 175
px = bytearray(W * H * 4)
TRANSP = (7, 8)
for n in range(19):
    col, row = n % 4, n // 4
    for y in range(16):
        for x in range(16):
            ch = TILES[n][y][x]
            i = ((row * 16 + y) * W + (col * 16 + x)) * 4
            if ch == ".":
                px[i:i+4] = bytes((0, 0, 0, 0))
            else:
                r, g, b = PAL[ch]
                px[i:i+4] = bytes((r, g, b, 175 if n == 10 else 255))
def chunk(t, d):
    import zlib, struct
    return struct.pack(">I", len(d)) + t + d + struct.pack(">I", zlib.crc32(t + d) & 0xffffffff)
raw = b"".join(b"\x00" + bytes(px[r * W * 4:(r + 1) * W * 4]) for r in range(H))
png = b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", struct.pack(">IIBBBBB", W, H, 8, 6, 0, 0, 0)) + chunk(b"IDAT", zlib.compress(bytes(raw), 9)) + chunk(b"IEND", b"")
open("assets/atlas.png", "wb").write(png)
print("atlas regenerado:", len(png), "bytes")
